### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by Zack7292** [HostaPlantain/Floricraft3#1]
### Issue

when i start there is an error, here is a screenie: 
![Screenshot_447](https://user-images.githubusercontent.com/45187146/82747085-f1117e00-9d63-11ea-82de-534843a0bcb6.png)

+ Floricraft3 version:0.23
+ Flora version:0.22
+ Minecraft version:1.15.2
+ Forge version:31.2.4
+ Other mods:none

**Comment by HostaPlantain** [comment]
caused by forge gradlew bug i'll rebuild it soon.

**Comment by HostaPlantain** [comment]
Thank you for reporting this issue. Flora and Floricraft3 have been rebuilded. Please have fun!
