### ISSUE TITLE
Flax seeds drop rate

### ISSUE THREAD

**Issue by VolvoRider** [HostaPlantain/Floricraft3#4]
### Issue

Hi, when I receive flax seeds from grass, i get a stack. I'm pretty sure it's a bug.

+ Floricraft3 version:
+ Flora version:
+ Minecraft version:
+ Forge version:
+ Other mods:

**Comment by HostaPlantain** [comment]
it cannot be reproduced. only a single flax seed drops from grass. 
it might caused by other mods in your mod pack.
